In [3]:
import numpy as np

In [3]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.dtype # 자동으로 형태를 정함

dtype('int64')

In [5]:
a = a.astype(np.float32) # a. astype('float32) 둘 중 아무거나 하나
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [6]:
a[0][1]  # 0행 1열

2.0

In [7]:
a[0]

array([1., 2., 3.], dtype=float32)

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1, 13).reshape(3, 2, 2) # 1~13 ~ shape 3, 2, 2형태로 만들어라 ! 갯수가 딱 맞아야함

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
np.nan * 10 #nan은 결측치로 곱하거나 더해도 변하지않음

nan

In [11]:
a[0][1] = np.nan # 결측치는 integer로 사용 불가 float로 가능

In [12]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

## 연산

In [13]:
data = np.arange(1,10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
data + data # numpy는 python과 다르게 각행렬이 더해짐 // 파이썬은 이어 붙여짐

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
data * data # 각행의 곱

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [17]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.dot(data, data) # 행렬의 곱

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
data@data # 행렬의 곱곱

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## 차원

In [29]:
# 0 차원 : scala
a = np.array([1])
a
# a.shape # 모양 NONE
# a.ndim  # 차원 : 0차원

array([1])

In [38]:
# 1 차원 : vector
a = np.array([1, 2, 3, 4, 5])
a
# a.shape # 모양 (5,) 5행 none열
# # a.ndim  # 차원 : 1차원

1

In [31]:
# 2 차원 : matrix
a = np.array([1, 2, 3], [4, 5, 6])
a
# a.shape # 모양 (2, 3) 2행 3열
# a.ndim  # 차원 : 0차원

array([1])

In [5]:
# 3 차원 : tensor 3차원 이상의 다차원 행렬
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
a
# a.shape # 모양 NONE
# a.ndim  # 차원 : 0차원

(2, 3, 2)

In [7]:
a = np.arange(12).reshape(2, 3, 2) # tensor
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
b = np.ones(12) # 1로 다 채워진 행렬
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
c = np.zeros(12).reshape(2, 3, 2) # 0으로 다 채워진 행렬
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
d = np.eye(3) # 단위 행렬
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
e = np.zeros([3, 4, 2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
f = np.empty([2, 3])
f

array([[-3.10503618e+231,  1.49458065e-154,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [17]:
g = np.full((3, 4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])